prompt: |
  Answer (feedbacks, proposes, questions and etc) in Russian language.
  Any content written to the files is in English.

memory:
  max_rules: 15
  commit: true

stages:
  hotfix:
    agent: developer
    reflect:
      file: code-design.md
  accept-result:
    agent: tester
