prompt: |
  Answer (feedbacks, proposes, questions:`*.question.json` and etc) in Russian language.
  Any content written to the project files is in English.

memory:
  max_rules: 15
  commit: true

stages:
  brainstorm:
    agent: architector
    reflect:
      file: architecture.md
  architecture-review:
    agent: reviewer
  apply-architecture:
    agent: architector
  code-design:
    agent: architector
    reflect:
      file: code-design.md
      mode: r
  design-review:
    agent: reviewer
  coding-plan:
    agent: architector
  plan-review:
    agent: reviewer
  accept-result:
    agent: tester
