prompt: |
  Answer (feedbacks, proposes, questions:`*.question.json` and etc) in Russian language.
  Any content written to the files is in English.

stages:
  define:
    skip: true
  discover:
    skip: true
  propose:
    agent: manager
  task-review:
    agent: reviewer